name: flutter_pagination_helper
description: A lightweight and reusable Flutter package for implementing pagination with minimal boilerplate. Includes paginated list/grid views and a powerful pagination mixin.
version: 1.0.2
homepage: https://github.com/munawerdev/flutter_pagination_helper
repository: https://github.com/munawerdev/flutter_pagination_helper
issue_tracker: https://github.com/munawerdev/flutter_pagination_helper/issues
topics:
  - pagination
  - infinite-scroll
  - listview
  - gridview
  - mixin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

# Package Structure:
# example/
#   └── main.dart
# lib/
#   ├── flutter_pagination_helper.dart (main export file)
#   ├── src/
#   │   ├── mixins/
#   │   │   └── pagination_mixin.dart
#   │   ├── widgets/
#   │   │   ├── paginated_list_view.dart
#   │   │   └── paginated_grid_view.dart